name: Release

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    name: Publish to Github Releases
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Publish Extension
      shell: bash
      run: |
        npx vsce package -o jsona-syntax.vsix
        npx vsce publish --pat ${{ secrets.MARKETPLACE_TOKEN }} --packagePath jsona-syntax.vsix

    - name: Publish Release
      uses: softprops/action-gh-release@v0.1.5
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        draft: false
        files: jsona-syntax.vsix
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
