name: Release

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  publish:
    name: Publish to Github Releases
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check Tag
      id: check-tag
      shell: bash
      run: |
        tag=${GITHUB_REF##*/}
        echo "::set-output name=version::$tag"
        if [[ "$tag" =~ [0-9]+.[0-9]+.[0-9]+$ ]]; then
          echo "::set-output name=rc::false"
        else
          echo "::set-output name=rc::true"
        fi

    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Publish Extension
      shell: bash
      run: |
        args=""
        if [[ "${{ steps.check-tag.outputs.rc }}" == "true" ]]; then
          args="--pre-release"
        fi
        npx vsce package -o jsona-syntax.vsix $args
        npx vsce publish --pat ${{ secrets.MARKETPLACE_TOKEN }} --packagePath jsona-syntax.vsix $args

    - name: Publish Release
      uses: softprops/action-gh-release@v0.1.5
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        draft: false
        files: jsona-syntax.vsix
        prerelease: ${{ steps.check-tag.outputs.rc == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
